const games = {
    "meta": {
        "code": 200,
        "count": 12,
        "description": "Games for NFL"
    },
    "results": [
        {
            "gameID": 485226,
            "team1Score": 14,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283123"
            ],
            "pointsLevel": "Elevated",
            "points": 112,
            "team1City": "Baltimore",
            "team2Name": "Bengals",
            "team1Initials": "BAL",
            "headline": "Bengals dominating the air attack (CIN 362, BAL 185)",
            "timeLeft": "3rd Quarter - 0:40",
            "team2ID": 13313,
            "team2Initials": "CIN",
            "rationale": "Individual Performance",
            "team1Color": "280353",
            "team2Score": 34,
            "team1Name": "Ravens",
            "round": "Week 16",
            "team2City": "Cincinnati",
            "team2Color": "ad3d19",
            "leagueCode": "FBP",
            "team1ID": 13309,
            "location": "Paul Brown Stadium",
            "time": 1640541600000,
            "highPoints": 140,
            "sport": "nfl"
        },
        {
            "gameID": 485225,
            "team1Score": 13,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283120"
            ],
            "pointsLevel": "Elevated",
            "points": 98,
            "team1City": "Detroit",
            "team2Name": "Falcons",
            "team1Initials": "DET",
            "headline": "Falcons are leading Lions 20-13, with 13:04 left in the 4th Quarter",
            "timeLeft": "4th Quarter - 13:04",
            "team2ID": 13308,
            "team2Initials": "ATL",
            "rationale": "Close Finish",
            "team1Color": "2f579e",
            "team2Score": 20,
            "team1Name": "Lions",
            "round": "Week 16",
            "team2City": "Atlanta",
            "team2Color": "820119",
            "leagueCode": "FBP",
            "team1ID": 13317,
            "location": "Mercedes-Benz Stadium",
            "time": 1640541600000,
            "highPoints": 98,
            "sport": "nfl"
        },
        {
            "gameID": 485232,
            "team1Score": 15,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283127"
            ],
            "pointsLevel": "Guarded",
            "points": 53,
            "team1City": "Los Angeles",
            "team2Name": "Texans",
            "team1Initials": "LAC",
            "headline": "Texans are leading Chargers 24-15, with 12:48 left in the 4th Quarter",
            "timeLeft": "4th Quarter - 12:48",
            "team2ID": 13319,
            "team2Initials": "HOU",
            "team1Color": "08214a",
            "team2Score": 24,
            "team1Name": "Chargers",
            "round": "Week 16",
            "team2City": "Houston",
            "team2Color": "001831",
            "leagueCode": "FBP",
            "team1ID": 13332,
            "location": "NRG Stadium",
            "time": 1640541600000,
            "highPoints": 88,
            "sport": "nfl"
        },
        {
            "gameID": 485230,
            "team1Score": 3,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283126"
            ],
            "pointsLevel": "Guarded",
            "points": 48,
            "team1City": "New York",
            "team2Name": "Eagles",
            "team1Initials": "NYG",
            "headline": "Eagles are leading Giants 13-3, with 6:53 left in the 3rd Quarter",
            "timeLeft": "3rd Quarter - 6:53",
            "team2ID": 13330,
            "team2Initials": "PHI",
            "team1Color": "192f6b",
            "team2Score": 13,
            "team1Name": "Giants",
            "round": "Week 16",
            "team2City": "Philadelphia",
            "team2Color": "003b48",
            "leagueCode": "FBP",
            "team1ID": 13327,
            "location": "Lincoln Financial Field",
            "time": 1640541600000,
            "highPoints": 56,
            "sport": "nfl"
        },
        {
            "gameID": 485229,
            "team1Score": 15,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283125"
            ],
            "pointsLevel": "Guarded",
            "points": 38,
            "team1City": "Jacksonville",
            "team2Name": "Jets",
            "team1Initials": "JAC",
            "headline": "Jaguars are trailing Jets 16-15, with 20 seconds left in the 3rd Quarter",
            "timeLeft": "3rd Quarter - 0:20",
            "team2ID": 13328,
            "team2Initials": "NYJ",
            "team1Color": "09586c",
            "team2Score": 16,
            "team1Name": "Jaguars",
            "round": "Week 16",
            "team2City": "New York",
            "team2Color": "213b1a",
            "leagueCode": "FBP",
            "team1ID": 13321,
            "location": "MetLife Stadium",
            "time": 1640541600000,
            "highPoints": 57,
            "sport": "nfl"
        },
        {
            "gameID": 485228,
            "team1Score": 20,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283121"
            ],
            "pointsLevel": "Guarded",
            "points": 36,
            "team1City": "Buffalo",
            "team2Name": "Patriots",
            "team1Initials": "BUF",
            "headline": "Bills are beating Patriots 20-13, with 1:41 left in the 3rd Quarter",
            "timeLeft": "3rd Quarter - 1:41",
            "team2ID": 13325,
            "team2Initials": "NE",
            "team1Color": "0e2675",
            "team2Score": 13,
            "team1Name": "Bills",
            "round": "Week 16",
            "team2City": "New England",
            "team2Color": "0d254c",
            "leagueCode": "FBP",
            "team1ID": 13310,
            "location": "Gillette Stadium",
            "time": 1640541600000,
            "highPoints": 57,
            "sport": "nfl"
        },
        {
            "gameID": 485231,
            "team1Score": 22,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283122"
            ],
            "pointsLevel": "Guarded",
            "points": 25,
            "team1City": "Tampa Bay",
            "team2Name": "Panthers",
            "team1Initials": "TB",
            "headline": "Panthers are trailing Buccaneers 22-6, with 3:45 left in the 3rd Quarter",
            "timeLeft": "3rd Quarter - 3:45",
            "team2ID": 13311,
            "team2Initials": "CAR",
            "team1Color": "d50a0a",
            "team2Score": 6,
            "team1Name": "Buccaneers",
            "round": "Week 16",
            "team2City": "Carolina",
            "team2Color": "3d71c7",
            "leagueCode": "FBP",
            "team1ID": 13336,
            "location": "Bank of America Stadium",
            "time": 1640541600000,
            "highPoints": 52,
            "sport": "nfl"
        },
        {
            "gameID": 485227,
            "team1Score": 20,
            "date": 1640541600000,
            "programIDs": [
                "EP000031283124"
            ],
            "pointsLevel": "Guarded",
            "points": 23,
            "team1City": "Los Angeles",
            "team2Name": "Vikings",
            "team1Initials": "LAR",
            "headline": "Vikings trail by 10, despite 3 turnovers by Rams",
            "timeLeft": "3rd Quarter - 2:19",
            "team2ID": 13324,
            "team2Initials": "MIN",
            "team1Color": "13264b",
            "team2Score": 10,
            "team1Name": "Rams",
            "round": "Week 16",
            "team2City": "Minnesota",
            "team2Color": "230086",
            "leagueCode": "FBP",
            "team1ID": 13335,
            "location": "U.S. Bank Stadium",
            "time": 1640541600000,
            "highPoints": 25,
            "sport": "nfl"
        },
        {
            "gameID": 485233,
            "date": 1640552700000,
            "team2ID": 13334,
            "programIDs": [
                "EP000031283128"
            ],
            "pointsLevel": "Guarded",
            "team2Initials": "SEA",
            "team1Color": "03202f",
            "points": 6,
            "team1Name": "Bears",
            "round": "Week 16",
            "team2City": "Seattle",
            "team1City": "Chicago",
            "team2Color": "acb6bc",
            "leagueCode": "FBP",
            "team1ID": 13312,
            "location": "Lumen Field",
            "team2Name": "Seahawks",
            "time": 1640552700000,
            "team1Initials": "CHI",
            "highPoints": 17,
            "sport": "nfl",
            "headline": "Seahawks play host to Bears and their 3-game losing streak"
        },
        {
            "gameID": 485235,
            "date": 1640553900000,
            "team2ID": 13329,
            "programIDs": [
                "EP000031283130"
            ],
            "pointsLevel": "Guarded",
            "team2Initials": "LVS",
            "team1Color": "002244",
            "points": 49,
            "team1Name": "Broncos",
            "round": "Week 16",
            "team2City": "Las Vegas",
            "team1City": "Denver",
            "team2Color": "a5a5a6",
            "leagueCode": "FBP",
            "team1ID": 13316,
            "location": "Allegiant Stadium",
            "team2Name": "Raiders",
            "time": 1640553900000,
            "team1Initials": "DEN",
            "highPoints": 70,
            "sport": "nfl",
            "headline": "Coming in with identical records, Raiders welcome Broncos, both looking to move above .500"
        },
        {
            "gameID": 485234,
            "date": 1640553900000,
            "team2ID": 13322,
            "programIDs": [
                "EP000031283129"
            ],
            "pointsLevel": "Guarded",
            "team2Initials": "KC",
            "team1Color": "202020",
            "points": 29,
            "team1Name": "Steelers",
            "round": "Week 16",
            "team2City": "Kansas City",
            "team1City": "Pittsburgh",
            "team2Color": "820119",
            "leagueCode": "FBP",
            "team1ID": 13331,
            "location": "GEHA Field at Arrowhead Stadium",
            "team2Name": "Chiefs",
            "time": 1640553900000,
            "team1Initials": "PIT",
            "highPoints": 59,
            "sport": "nfl",
            "headline": "Steelers will need to slow down Kelce (191 Yds, 2 TDs in last game) as they visit Chiefs"
        },
        {
            "gameID": 485236,
            "date": 1640568000000,
            "team2ID": 13315,
            "programIDs": [
                "EP000031283131"
            ],
            "pointsLevel": "Guarded",
            "team2Initials": "DAL",
            "team1Color": "620012",
            "points": 38,
            "team1Name": "Football Team",
            "round": "Week 16",
            "team2City": "Dallas",
            "team1City": "Washington",
            "team2Color": "8c8b8a",
            "leagueCode": "FBP",
            "team1ID": 13338,
            "location": "AT&T Stadium",
            "team2Name": "Cowboys",
            "time": 1640568000000,
            "team1Initials": "WAS",
            "highPoints": 43,
            "sport": "nfl",
            "headline": "Football Team stand in the way of Cowboys and their 4th straight win"
        }
    ]
}
// console.log(games.results)
export default games;